# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerName', models.CharField(max_length=32)),
                ('export_time', models.DateTimeField()),
                ('count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=16)),
                ('orderid', models.CharField(max_length=32)),
                ('receiver_name', models.CharField(max_length=8)),
                ('receiver_address', models.CharField(max_length=64)),
                ('receiver_zip', models.CharField(default='', max_length=6, null=True)),
                ('receiver_mobile', models.CharField(max_length=11)),
                ('seller_memo', models.CharField(default='', max_length=255, null=True)),
                ('buyer_remark', models.CharField(default='', max_length=255, null=True)),
                ('jancode', models.CharField(default='', max_length=24, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=7, null=True)),
                ('delivery_type', models.CharField(max_length=32)),
                ('piad_time', models.DateTimeField()),
                ('product_title', models.CharField(max_length=255)),
                ('sku_properties_name', models.CharField(default='', max_length=64, null=True)),
                ('status', models.CharField(default='待处理', max_length=3, null=True)),
                ('order_inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Inventory', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='outStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jancode', models.CharField(max_length=24, unique=True)),
                ('category', models.CharField(max_length=32, null=True)),
                ('band', models.CharField(max_length=32, null=True)),
                ('origin', models.CharField(max_length=64, null=True)),
                ('catalog', models.CharField(max_length=64, null=True)),
                ('color', models.CharField(max_length=8, null=True)),
                ('proddesc', models.CharField(max_length=255, null=True)),
                ('unit', models.CharField(max_length=2, null=True)),
                ('expired', models.CharField(max_length=8, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('purchaseprice', models.DecimalField(decimal_places=5, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('delivery_id', models.CharField(blank=True, max_length=255)),
                ('cost', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('status', models.CharField(default='create', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('po_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Inventory', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('inflight', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=8, null=True)),
                ('inventory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Inventory', to_field='name')),
                ('product_jancode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product', to_field='jancode')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('interval', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Supplier', to_field='name'),
        ),
        migrations.AlterUniqueTogether(
            name='exportorderlog',
            unique_together=set([('sellerName', 'export_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('channel', 'orderid', 'jancode')]),
        ),
    ]
