# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=18)),
                ('category_cn_name', models.CharField(max_length=64)),
                ('category_en_name', models.CharField(max_length=64, null=True)),
                ('category_level', models.IntegerField()),
                ('category_parent_id', models.CharField(max_length=18)),
                ('category_version', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='ExportOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerName', models.CharField(max_length=32)),
                ('export_time', models.DateTimeField()),
                ('count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=32)),
                ('channel_name', models.CharField(max_length=16)),
                ('orderid', models.CharField(max_length=32)),
                ('receiver_name', models.CharField(max_length=8)),
                ('receiver_address', models.CharField(max_length=64)),
                ('receiver_zip', models.CharField(default='', max_length=6, null=True)),
                ('receiver_mobile', models.CharField(max_length=11)),
                ('receiver_idcard', models.CharField(max_length=18, null=True)),
                ('seller_memo', models.CharField(default='', max_length=255, null=True)),
                ('buyer_remark', models.CharField(default='', max_length=255, null=True)),
                ('jancode', models.CharField(default='', max_length=24, null=True)),
                ('quantity', models.IntegerField()),
                ('need_purchase', models.IntegerField(default=0, null=True)),
                ('allocate_time', models.DateTimeField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('delivery_type', models.CharField(max_length=32)),
                ('piad_time', models.DateTimeField()),
                ('product_title', models.CharField(max_length=255)),
                ('sku_properties_name', models.CharField(default='', max_length=64, null=True)),
                ('status', models.CharField(default='待处理', max_length=3, null=True)),
                ('importstatus', models.CharField(max_length=3, null=True)),
                ('conflict', models.CharField(max_length=8, null=True)),
                ('conflict_memo', models.CharField(max_length=128, null=True)),
                ('conflict_feedback', models.CharField(max_length=128, null=True)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='stock.Inventory')),
            ],
            options={
                'ordering': ['piad_time', 'receiver_mobile'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jancode', models.CharField(max_length=24, unique=True)),
                ('brand', models.CharField(max_length=128, null=True)),
                ('origin', models.CharField(max_length=64, null=True)),
                ('model', models.CharField(max_length=128, null=True)),
                ('specification', models.CharField(max_length=128, null=True)),
                ('size', models.CharField(max_length=128, null=True)),
                ('proddesc', models.CharField(max_length=255, null=True)),
                ('unit', models.CharField(max_length=2, null=True)),
                ('expired', models.CharField(max_length=8, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='stock.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=64)),
                ('delivery_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='create', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder', to='stock.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('jancode', models.ForeignKey(db_column='jancode', on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem', to='stock.Product', to_field='jancode')),
                ('purchaseorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem', to='stock.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('delivery_company', models.CharField(max_length=4, null=True)),
                ('tiangou_company', models.CharField(default='', max_length=4, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='stock.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_number', models.CharField(max_length=32, null=True)),
                ('channel_name', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=8, null=True)),
                ('ymatou', models.CharField(max_length=8, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingdb', to='stock.Inventory')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingdb', to='stock.Shipping')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('inflight', models.IntegerField(default=0, null=True)),
                ('preallocation', models.IntegerField(default=0, null=True)),
                ('location', models.CharField(max_length=8, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock.Inventory')),
                ('jancode', models.ForeignKey(db_column='jancode', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock.Product', to_field='jancode')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('interval', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder', to='stock.Supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchaseorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='stock.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='stock.Shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingdb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='stock.ShippingDB'),
        ),
        migrations.AlterUniqueTogether(
            name='exportorderlog',
            unique_together=set([('sellerName', 'export_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([('inventory', 'jancode')]),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together=set([('orderid', 'supplier')]),
        ),
    ]
