# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='channel',
            new_name='channel_name',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('channel_name', 'orderid', 'jancode')]),
        ),
    ]
