# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20170707_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
