# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_order_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchaseprice',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
