# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20170707_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_jancode',
        ),
        migrations.AddField(
            model_name='stock',
            name='jancode',
            field=models.CharField(default='', max_length=24, null=True),
        ),
    ]
