# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20170707_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
