# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stock_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='jancode',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
