# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20170707_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='preallocation',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
