# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stock_preallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('shipping_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Inventory', to_field='name')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Shipping'),
        ),
    ]
