# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20170711_1537'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([]),
        ),
    ]
