# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20170713_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='inventory_name',
            field=models.CharField(max_length=8),
        ),
    ]
