# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20170714_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='inventory_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Inventory', to_field='name'),
        ),
    ]
